# Generated by Django 4.1 on 2023-02-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shope', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
